### PR TITLE
Add register v4

### PR DESCRIPTION
**Pull request by Overload119**
Early pull request, so you can see what I'm doing.
I'll wrap this up later tonight.

Still have to fix some API endpoints and test some other things.

screen shot 2016-02-01 at 2 05 27 pm

### CODE REVIEW

**Comment by Overload119** [comment]
Okay - this should be good to review now.

Ask any questions you have here - even if they're small - I can probably explain them better than if you googled it.

screen shot 2016-02-01 at 9 10 32 pm

**Comment by jaytj95** [comment]
image

I just made a login using Postman. Username: jaytj95@gmail.com Password: test1234. I'm unable to login (or register, for that matter) via the app. I'm on this branch and not the latest one you pushed. Have you seen this?

**Comment by Overload119** [comment]
In that screenshot it shows a success.
I just logged in on web and it worked as well.
If the app logging in isn't working I would check the endpoint in API.js (make sure it's set to rappad) and then setup a debugger to see if you can get a breakpoint around when the API request is sent (so you can inspect the response).

**Comment by jaytj95** [comment]
Yeah I created the account using Postman and it showed a success. In the app though, when trying to log in, it doesn't work. The API.js is set to rappad. I'll look into setting up a debugger to see what's going on. Are you using a third party emulator or the Android-provided one? I'm using [Genymotion](https://www.genymotion.com/)

**Comment by jaytj95** [comment]
I was able to login via the app. Turns out the internet connection on my laptop wasn't passing through to the emulator properly. All good now. Thanks!

**Pull request merged**
